# test.yml - GitHub Actions tests
# Copyright 2020 Dean Scarff
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: vivian
on:
  push:
  schedule:
    # Weekly on Thursdays at 03:13.
    - cron: '13 3 * * 4'

jobs:
  test:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [ '/Applications/Xcode_13.2.1.app' ]
    env:
      DEVELOPER_DIR: ${{ matrix.xcode }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure SPM cache
      uses: actions/cache@v2
      with:
        path: .spm
        key: spm-${{ runner.os }}-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          spm-${{ runner.os }}-${{ matrix.xcode }}-
          spm-${{ runner.os }}-
    - name: Update Homebrew
      run: |
        brew update --preinstall
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/"{clang,swift}-format.rb > .github/brew-formulae
    - name: Configure Homebrew cache
      uses: actions/cache@v2
      with:
        # brew --cache
        path: |
          ~/Library/Caches/Homebrew/clang-format--*
          ~/Library/Caches/Homebrew/swift-format--*
          ~/Library/Caches/Homebrew/downloads/*--clang-format*
          ~/Library/Caches/Homebrew/downloads/*--swift-format*
        key: brew-${{ hashFiles('.github/brew-formulae') }}
        restore-keys: |
          brew-
    - name: Install Homebrew dependencies
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install clang-format swift-format
    - name: Lint
      run: |
        find viv -name '*.[h,m,mm]' -exec clang-format -n '{}' '+'
        swift-format lint --recursive vivtool vivtoolTests
    - name: Build and test
      run: |
        xcodebuild test -scheme vivtool -clonedSourcePackagesDirPath .spm -disableAutomaticPackageResolution
