# test.yml - GitHub Actions tests
# Copyright 2020 Dean Scarff
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: vivian
on:
  push:
  schedule:
    # Weekly on Thursdays at 03:13.
    - cron: '13 3 * * 4'

jobs:
  test:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [ '/Applications/Xcode_12.app' ]
    env:
      DEVELOPER_DIR: ${{ matrix.xcode }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure SPM cache
      uses: actions/cache@v2
      with:
        path: .spm
        key: spm-${{ runner.os }}-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          spm-${{ runner.os }}-${{ matrix.xcode }}-
          spm-${{ runner.os }}-
    - name: Build and test
      run: |
        xcodebuild test -scheme vivtool -clonedSourcePackagesDirPath .spm -disableAutomaticPackageResolution
